// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Wqtlnt8SOuVjEK4E0wFaoVy0P76TPKQ',
    appId: '1:1029542215739:web:9ccb33613626f95df05c1e',
    messagingSenderId: '1029542215739',
    projectId: 'geo-scanner-a3b3a',
    authDomain: 'geo-scanner-a3b3a.firebaseapp.com',
    storageBucket: 'geo-scanner-a3b3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuBAXz4P8wf0W4eKamUFN3VB8OG9ykpVc',
    appId: '1:1029542215739:android:11e856499f422765f05c1e',
    messagingSenderId: '1029542215739',
    projectId: 'geo-scanner-a3b3a',
    storageBucket: 'geo-scanner-a3b3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmI1J2ceVHnRavyB5j7uIaS6Spq0IEhJQ',
    appId: '1:1029542215739:ios:2dbd8623416077edf05c1e',
    messagingSenderId: '1029542215739',
    projectId: 'geo-scanner-a3b3a',
    storageBucket: 'geo-scanner-a3b3a.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmI1J2ceVHnRavyB5j7uIaS6Spq0IEhJQ',
    appId: '1:1029542215739:ios:2dbd8623416077edf05c1e',
    messagingSenderId: '1029542215739',
    projectId: 'geo-scanner-a3b3a',
    storageBucket: 'geo-scanner-a3b3a.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Wqtlnt8SOuVjEK4E0wFaoVy0P76TPKQ',
    appId: '1:1029542215739:web:9a84d810231aa888f05c1e',
    messagingSenderId: '1029542215739',
    projectId: 'geo-scanner-a3b3a',
    authDomain: 'geo-scanner-a3b3a.firebaseapp.com',
    storageBucket: 'geo-scanner-a3b3a.firebasestorage.app',
  );
}
